export const ADD_GROUP = "ADD_GROUP";
export const START_LOADING_GROUPS = "START_LOADING_GROUPS";
export const SUCCESSFULLY_LOADED_GROUPS = "SUCCESSFULLY_LOADED_GROUPS";
export const FAILED_LOADING_GROUPS = "FAILED_LOADING_GROUPS";