// groups
export const START_LOADING_GROUPS = "START_LOADING_GROUPS";
export const SUCCESSFULLY_LOADED_GROUPS = "SUCCESSFULLY_LOADED_GROUPS";
export const SUCCESSFULLY_CREATED_GROUP = "SUCCESSFULLY_CREATED_GROUP";

// actions occuring on /groups/:id/
export const START_LOADING_GROUP = "START_LOADING_GROUP";
export const SUCCESSFULLY_LOADED_GROUP_EVENTS = "SUCCESSFULLY_LOADED_GROUP_EVENTS"

// not implemented yet
export const ADD_GROUP = "ADD_GROUP"; 
export const FAILED_LOADING_GROUPS = "FAILED_LOADING_GROUPS"; 


// events
export const SUCCESSFULLY_CREATED_EVENT = "SUCCESSFULLY_CREATED_EVENT";